# Generated by Django 5.0.6 on 2024-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("miapp", "0002_articulo_imagen_alter_articulo_titulo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Autor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("apellido", models.CharField(max_length=50)),
                ("sexo", models.BooleanField()),
                ("fecha_nac", models.DateField()),
                ("pais", models.BooleanField()),
            ],
        ),
    ]
